name: ant
channels:
        - conda-forge
        - default
dependencies:
        - python=3.8
        - numpy==1.21.5
        - pandas==1.4.1
        - scipy
        - matplotlib
        - pip
        - pip:
                - ipykernel
